version: "3"

services:
  
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/:/etc/loki
      - ./data/loki/:/tmp/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    restart: unless-stopped
    depends_on: 
      - grafana

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
        - ./config/grafana.ini:/etc/grafana/grafana.ini
        - ./data/grafana/:/var/lib/grafana/
    ports:
        - "3000:3000"
    user: "472"
    environment:
      GF_EXPLORE_ENABLED: "true"
    logging:
      driver: loki
      options:
        loki-url: "http://212.64.58.168:3100/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "400"

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
        - ./config/promtail/:/etc/promtail
        - ./var/log:/var/log
    command:
        -config.file=/etc/promtail/promtail-docker-config.yaml
    ports:
        - "9080:9080"

  loki_conn:
    image: hellodudu86/loki_conn
    container_name: loki_conn
    command:
        -url="http://loki:3100/api/prom/push"
    depends_on:
        - loki
